version: "3"

services:
  v-proxy:
    image: nginx
    container_name: v-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/conf.d/custom.conf:/etc/nginx/conf.d/custom.conf
      - ./proxy/conf.d:/etc/nginx/conf.d
    networks:
      v-net:
        ipv4_address: 172.14.1.2

  v-mysql:
    image: mysql:5.7
    container_name: v-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Fruit
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: mysqladmin ping
    ports:
      - "3306:3306"
    networks:
      v-net:
        ipv4_address: 172.14.1.3

  v-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: v-phpmyadmin
    depends_on:
      - v-mysql
    external_links:
      - v-mysql:mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Fruit
      MYSQL_PASSWORD: 123456
      PMA_HOST: v-mysql
      VIRTUAL_HOST: phpmyadmin.local
    networks:
      v-net:
        ipv4_address: 172.14.1.5

  v-laravel-api:
    build: ../V-Laravel-Api
    image: v-laravel-api
    container_name: v-laravel-api
#    depends_on:
#      v-mysql:
#        condition: service_healthy
    networks:
      v-net:
        ipv4_address: 172.14.1.4
    volumes:
      - ../V-Laravel-Api:/var/www/html
    hostname: api
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Fruit
      MYSQL_PASSWORD: 123456
      PMA_HOST: v-mysql
      APP_ENV: local
      VIRTUAL_HOST: v-api.local

  v-vue-console:
    build: ../V-Console
    image: v-vue-console
    container_name: v-vue-console
    networks:
      v-net:
        ipv4_address: 172.14.1.6
    volumes:
      - ../V-Console:/app
      - ./supervisor/conf.d/vue-worker.conf:/etc/supervisor/conf.d/vue-worker.conf
    hostname: console
    environment:
      VIRTUAL_HOST: v-console.local

networks:
  v-net:
    name: v-net
    ipam:
      config:
        - subnet: 172.14.1.0/16
